# Generated by Django 3.1 on 2020-08-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catregory',
            new_name='Category',
        ),
    ]
